server:
  port: 8001

spring:
  application:
    name: consul-provider-payment
#    name: hytrix-provider-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
