server:
  port: 80

spring:
  application:
    name: hytrix-consumer-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#客户端适用服务降级
feign:
  hystrix:
    enabled: true
